### ISSUE TITLE
FATAL ERROR FATAL ERROR FATAL ERROR FATAL ERROR FATAL ERROR FATAL ERROR FATAL ERROR FATAL ERROR FATAL ERROR FATAL ERROR FATAL ERROR FATAL ERROR FATAL ERROR 

### ISSUE THREAD

**Issue by krvvko** [NicholasKuselov/TradeUp_Helper#2]
![Screenshot_9](https://user-images.githubusercontent.com/75450127/134082228-c2f85ab2-72de-41cf-b7ce-7148e245b43f.png)
ахуенная разработка! 10 FATAL ERROR/10

**Comment by NicholasKuselov** [comment]
Ахах

**Comment by NicholasKuselov** [comment]
В папке программы есть папка data, там есть папка logs. Скинь все что там есть плз

**Comment by NicholasKuselov** [comment]
Пофикшено
